/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Juan
 */
public class perceptronView extends javax.swing.JFrame {

    /**
     * Creates new form perceptronView
     */
    public perceptronView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        evaluateButton = new javax.swing.JButton();
        validateButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        setVarButton = new javax.swing.JButton();
        learningCoefficent = new javax.swing.JLabel();
        threshold = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        test = new javax.swing.JButton();
        gate = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        evaluateButton.setText("Evaluar");
        getContentPane().add(evaluateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 11, 105, -1));

        validateButton.setText("Comprobar");
        getContentPane().add(validateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 11, 105, -1));

        backButton.setText("Volver");
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 11, 105, -1));

        setVarButton.setText("Inicar Variables");
        setVarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setVarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(setVarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        learningCoefficent.setText("0");
        getContentPane().add(learningCoefficent, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 260, 40, -1));

        threshold.setText("0");
        getContentPane().add(threshold, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 40, -1));

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 200));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 1000, 200));

        test.setText("Probar");
        getContentPane().add(test, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        gate.setText("jLabel1");
        getContentPane().add(gate, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 50, 210, 110));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1020, 279));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setVarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setVarButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setVarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perceptronView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perceptronView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perceptronView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perceptronView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perceptronView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton backButton;
    public javax.swing.JLabel background;
    public javax.swing.JButton evaluateButton;
    public javax.swing.JLabel gate;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JLabel learningCoefficent;
    public javax.swing.JButton setVarButton;
    public javax.swing.JButton test;
    public javax.swing.JLabel threshold;
    public javax.swing.JButton validateButton;
    // End of variables declaration//GEN-END:variables
}
